spring:
  application:
    name: payment-service



  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      retries: 10


  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true&serverTimezone=Europe/Berlin
    username: root
    password: root4Web!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8086}
  servlet:
    context-path: /payment-service



app:
  kafka:
    consumer:
      group-id: payment-service

    topics:
      order-created: order.created
      payment-completed: payment.completed

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.orm.jdbc.extract: OFF

management:
  endpoints:
    web:
      exposure:
        include: health,info

