server:
  port: 8080
  servlet:
    context-path: /order-service

spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      acks: all
      retries: 10
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:order-service}
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.gwatcho.orderservice.event
        spring.json.value.default.type: com.gwatcho.orderservice.event.DeliveryCompletedEvent
        spring.json.use.type.headers: false

  datasource:
    url: jdbc:mysql://order-db:3306/order_db?createDatabaseIfNotExist=true&serverTimezone=Europe/Berlin
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gwatcho-shop
          jwk-set-uri: http://keycloak:8080/realms/gwatcho-shop/protocol/openid-connect/certs



services:
  product-service:
    url: http://product-service:8080/product-service

app:
  kafka:
    consumer:
      group-id: order-service
    topics:
      order-created: order.created
      delivery-completed: delivery.completed

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.orm.jdbc.extract: OFF

management:
  endpoints:
    web:
      exposure:
        include: health,info

