
spring:
  application:
    name: order-service


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      retries: 10

  datasource:
    url: jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true&serverTimezone=Europe/Berlin
    username: root
    password: root4Web!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gwatcho-shop

server:
  port: 8082
  servlet:
    context-path: /order-service

services:
  product-service:
    url: http://localhost:8083/product-service

app:
  kafka:
    consumer:
      group-id: order-service
    topics:
      order-created: order.created
      delivery-completed: delivery.completed

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.orm.jdbc.extract: OFF

management:
  endpoints:
    web:
      exposure:
        include: health,info

